sudo: false

language: node_js
node_js:
  - "17"

cache: npm

branches:
  only:
    - master # build master branch only

script:
  - hexo generate # generate static files

deploy:
  provider: pages
  cleanup: true
  token: $GH_TOKEN
  keep_history: true
  fqdn: stephenfang.me
  on:
    branch: master
  local_dir: public
